http {
    lua_shared_dict upstream_cache 10m;

    lua_package_path "/usr/local/openresty/lualib/proxy.lua;;";

    server {
        listen 80;
        listen 443 ssl;

        server_name *;

        ssl_certificate     /var/tls/fullchain.pem;
        ssl_certificate_key /var/tls/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;

        set $target_url "";

        location / {
            access_by_lua_file /etc/nginx/lua/proxy.lua;

            proxy_pass http://$target_url;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}